"""
ComfyUI nodes for Maya1 TTS.
"""

from .maya1_tts_combined import (
    Maya1TTSCombinedNode,
    NODE_CLASS_MAPPINGS as COMBINED_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as COMBINED_DISPLAY_MAPPINGS
)

from .maya1_tts_barebones import (
    Maya1TTSBarebonesNode,
    NODE_CLASS_MAPPINGS as BAREBONES_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as BAREBONES_DISPLAY_MAPPINGS
)

from .maya1_tts_gguf import (
    Maya1TTS_GGUF,
    NODE_CLASS_MAPPINGS as GGUF_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GGUF_DISPLAY_MAPPINGS
)

# Merge the mappings from all nodes
NODE_CLASS_MAPPINGS = {**COMBINED_MAPPINGS, **BAREBONES_MAPPINGS, **GGUF_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**COMBINED_DISPLAY_MAPPINGS, **BAREBONES_DISPLAY_MAPPINGS, **GGUF_DISPLAY_MAPPINGS}

__all__ = [
    "Maya1TTSCombinedNode",
    "Maya1TTSBarebonesNode",
    "Maya1TTS_GGUF",
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
